# Tokenomics Resources

## Tokenomics 101 Level Content

### Intro to Tokenomics
**[All You Need to Know About Tokenomics](https://medium.com/coinmonks/all-you-need-to-know-about-tokenomics-39642fe11d02)**
- Basics of tokenomics and overview of the key variables: supply, burning, monetary policy, token distribution and earnings

**[An Introduction to Token Economics](https://alexbeckett.medium.com/an-introduction-to-token-economics-tokenomics-c6eb9211778f)**
- Exploring supply and demand drivers for tokens, with a high level overivew on token distribution for UNI 

**[Tokenomics 101: The Basics of Evaluating Cryptocurrencies](https://every.to/almanack/tokenomics-101)**
- Tokenomics breakdown through the lens of supply + demand as opposed to the underlying driveres (e.g. burning, monetary policy, etc.), with a high-level analysis on Convex Finance

### Protocol Tokenomics Overviews
_Analysis/articles covering initial tokenomics, governing principles and associated tradeoffs made when designing incentives compared to other protocols_

- [Near Protocol](https://near.org/blog/near-protocol-economics/)
- Harmony One
  - [Initial Token Economic Model](https://blog.harmony.one/harmony-token-economic-model/)
  - [Updated Token Economic Model](https://blog.harmony.one/harmonys-new-tokenomics/)
  - [Economic Model](https://docs.google.com/spreadsheets/d/1bcABBb47X8jOAQC-Dno9A9HFtLf8vlRp70P9xVqjhG4/edit#gid=1322834538)
- [Ethereum Tokenomics 2021: Impact of Eth2, EIP 1559 and L2 Scaling Solutions on Demand/Supply](https://hackernoon.com/ethereum-tokenomics-2021-impact-of-eth2-eip-1559-and-l2-scaling-solutions-on-demandsupply-gx5034tw)
  - Slightly outdated, but helpful illustration of how infrastructure changes impact supply/demand dynamics for ETH (or other asset)

### Advanced Content
- A Hitchiker's Guide to Token Engineering
  - [Substack](https://ahitchhikers.substack.com/)
  - [Cryptoeconomic Patterns](https://docs.google.com/presentation/d/1j4aNHhpaxUJjJ-DmnG2DC_zCGDc65oq-ND7zHNrmeKk/edit#slide=id.p)

## Tokenomics Evaluation Framework
_High level framework / key questions for evaluating tokenomics_

**Supply**

Key Question(s): Based on supply alone, will this token hold or increase it's value? Or will that be inflated away?

**Total Supply**
- How many tokens exist today?
- How many will ever exist? (e.g. is there a supply cap in place?)

**Issuance Rate**
- Is the issuance rate fixed or variable?
- If variable, what are the factors that determine (and can influence) issuance rates?

**Allocation/Vesting**
- How was the supply initially allocated among investors, community, core team, etc?
- Are there any holder(s) with a significant stake that could drive material selling pressure upon vesting?
- What is the vesting schedule for the largest holders?

**Demand**

Key Question: Why would someone hold this token?

**ROI**
- Excluding any price appreciation, what return is generated by simply holding the token?
- Is there an opportunity to earn an additional return by yield farming?
- Are earnings/fees generated from the protocol distributed back to token holders?
- Does any "rebasing" take place as the protocol inflates?
  _Rebasing works stimilar to a stock split, whereby holding and staking the token enables the holder to receive more, thereby offsetting any impact of inflation and holding % ownership constant_

**Community**
- How active is the Discord/Twitter?
- Have any grants, hackathons or ecosystem funds been announced?
- How is the protocol actively working to drive additional community engagement?
- Do one-time + ongoing initiatves drive additional token demand?

**Lockups**
- Is there a lockup program in place?
- If there is a lockup program in place, what is the incremental value of rewards and what are the requirements to earn those rewards?
- What % of total tokens outstanding are locked up?
- How much selling pressure is generated upon lockup expiration (and at what dates)?
- Are there other non-monetary benefits to staking + locking up tokens? For example, does staking result in increased voting power?

## DAO-specific Content
- [Interactive Design & Tooling for DAOs](https://blog.aragon.org/incentive-design-tooling-for-daos/)
