name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

input: ./docs
url: fstrauf.github.io/tokenomicsDAO
branding:
  title: TokenomicsDAO
  label: Docs
footer:
  copyright: "&copy; Copyright {{ year }}. All rights reserved."

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@v1

      - uses: retypeapp/action-github-pages@v1
        with:
          update-branch: true